# Generated by Django 2.1.3 on 2018-11-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id_author', models.IntegerField(db_column='ID_author', primary_key=True, serialize=False)),
                ('author', models.TextField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AUTHORS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id_book', models.IntegerField(db_column='ID_book', primary_key=True, serialize=False)),
                ('author', models.TextField(blank=True, null=True)),
                ('book_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BOOKS',
                'managed': False,
            },
        ),
    ]
